In [1]:
# This is about implementing a Logistic Regression model

In [2]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [3]:
diabetes_dataset = pd.read_csv(r"C:\Users\Emmanuel\Desktop\Dataset\diabetes.csv")

In [4]:
diabetes_dataset.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [5]:
diabetes_dataset.shape

(768, 9)

In [6]:
diabetes_dataset.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [7]:
diabetes_dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [8]:
# Separating the data and labels 
features = diabetes_dataset.drop(columns= 'Outcome', axis = 1)
target = diabetes_dataset['Outcome']

In [9]:
# Data Standardization 

scaler = StandardScaler()
scaler.fit(features)
standardized_data = scaler.transform(features)

In [10]:
print(standardized_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [11]:
features = standardized_data
target = diabetes_dataset["Outcome"]

In [12]:
# Train Test Split 

X_train, X_test, Y_train, Y_test = train_test_split(features, target, test_size= 0.2, random_state=2)

In [31]:
# Logistic Regression 

class Logistics_Regression():

    # declaring Learning rate and Number of Iteration (Hyperparameters)
    def __init__(self, Learning_rate, no_of_iteration):

        self.Learning_rate = Learning_rate
        self.no_of_iteration = no_of_iteration

    # Fit function to train the model with dataset
    def fit(self, X, Y):

        #[rows, input features], rows = m, input features = n
        self.m, self.n = X.shape 


        #initiating weight and bias values 
        self.w = np.zeros(self.n)

        self.b = 0

        self.X = X

        self.Y = Y

        # Implementing gradient descent for optimization 
        for i in range(self.no_of_iteration):
            self.update_weights()     


    def update_weights(self):

        # Y_hat formulat (Sigmoid function)
        Y_hat = 1 / (1 + np.exp( - (self.X.dot(self.w) + self.b)))

        # derivatives 
        dw = (1 / self.m)*np.dot(self.X.T, (Y_hat - self.Y))

        db = (1 / self.m)*np.sum(Y_hat - self.Y)

        # Updating the weight and bias using gradient descent equation 
        self.w = self.w - self.Learning_rate * dw 
        self.b = self.b - self.Learning_rate * db 

    # Sigmoid function and Decision making
    def predict(self, X):

        Y_pred = 1 / (1 + np.exp( - (X.dot(self.w) + self.b)))
        Y_pred = np.where(Y_pred > 0.5, 1, 0)
        return Y_pred

In [33]:
classifier = Logistics_Regression(Learning_rate=0.01, no_of_iteration=1000)

In [34]:
# Training the support vector Machine Classifier

classifier.fit(X_train, Y_train)

In [35]:
# Model Evaluation 

# Accuracy Score 
# accuracy score on the training data 

X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(Y_train, X_train_prediction)

In [36]:
print('Accuracy score of the training data : ', training_data_accuracy)

Accuracy score of the training data :  0.7768729641693811

In [37]:
X_test_prediction = classifier.predict(X_test)
test_data_accuracy = accuracy_score(Y_test, X_test_prediction)
print('Accuracy score of the training data : ', test_data_accuracy)

Accuracy score of the training data :  0.7662337662337663

In [39]:
# Making Predictive system 

input_data = (5, 166, 72, 19, 175, 25.8, 0.587, 51)

# Changing the input_data to numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the array for predicting one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1, -1)

# Standardize the input data 
std_data = scaler.transform(input_data_reshaped)
print(std_data)

prediction = classifier.predict(std_data)
print(prediction)

if (prediction[0] == 0):
    print('The person is not diabetic')
else:
    print('The person is diabetic')

[[ 0.3429808   1.41167241  0.14964075 -0.09637905  0.82661621 -0.78595734
   0.34768723  1.51108316]]
[1]
The person is diabetic

c:\Users\Emmanuel\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(